# Docker-Ansible-Gitlab CI/CD Pipeline

image: docker:20.10.16  # une version stable qui supporte tout bien

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache docker-compose

stages:
  - build
  - deploy
  - test
  - cleanup

build_images:
  stage: build
  script:
    - echo "Building Docker images for ssh_server and ansible_controller"
    - docker-compose -f docker-compose.yml build
  tags:
    - docker

deploy_nginx:
  stage: deploy
  script:
    - echo "Deploying NGINX using Ansible"
    - docker-compose up -d ssh_server ansible_controller
    - sleep 10
    - docker-compose exec ansible_controller ansible-playbook -i ansible/inventory ansible/playbook.yml
    - docker-compose exec ssh_server curl localhost:80
  tags:
    - docker

test_nginx:
  stage: test
  script:
    - echo "Testing NGINX deployment"
    - docker-compose exec ssh_server curl localhost:80
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up containers"
    - docker-compose down
  tags:
    - docker